### ISSUE TITLE
#unfolded

### ISSUE THREAD

**Issue by hahnlab-user** [BioPP/grapes#2]
In the README the example for using the unfolded SFS doesn't make sense to me--there are more than n-1 apparent entries for counts, and they jump to a much higher number part way through. Does this example work?

thanks,
Matt

**Comment by jydu** [comment]
The entry file does not only contain the SFS, but also number of sites, etc. The format for the unfolded SFS is the same as for the folded one, see complete description just above (and the DOFE documentation for more details).

**Comment by hahnlab-user** [comment]
Hi Julien, Thanks for responding so quickly. I get that there are numbers of sites in there (and some other things), but I still cannot make any sense of this example. Here is the important line:

all_genes 12 1.61188e+06 2008.19 590.033 73.6923 61.4066 63.5934 65.3077 5046.4 2095.86 836.505 533.066 327.066 318.044 322.549 518.198 432574 38940 165.33 104.637 403.44 757.527 109.824 85.956 119.604 361114 357.615 1.48228e+06 13089 

Which are the number of synonymous sites for polymorphism? For nonsynonymous? How many entries in the SFS are there (there should only be 11)? Any help in annotating this would be appreciated.


matt

**Comment by jydu** [comment]
dear Matt,

Indeed this was a mess! Most likely an error when converting from PDF to Markdown... this is now fixed, thanks a lot for reporting this!
