### ISSUE TITLE
Problems with installing grapes in macOS

### ISSUE THREAD

**Issue by izabelcavassim** [BioPP/grapes#3]
Hi, I have tried to install this software in macOs with the required dependencies, and this is what I get:

/grapes-master/grapes/Grapes.cpp:8:10: fatal error: 'values.h' file not found

By googling it I can see that values.h  is deprecated in C and one should use limits.h instead.
When I comment out //#include <values.h> from the Grapes.cpp file I get the following message:

/grapes-master/grapes/Grapes.cpp:2118:18: error: use of undeclared identifier 'DBL_MAX'

Then I decide to define the 'DBL_MAX' within the header as follow:
#define DBL_MAX 1.79769e+308

Everything compiles smoothly!!

I just wanna know if making these modifications will cause any issue to the stability of the software. I am not very familiar with c++, so I can't tell. 
Thanks!!

**Comment by jydu** [comment]
Hi Izabel,

I had the impression I had fixed that already :s the modern way of coding this is to replace DBL_MAX by std::numeric_limits<double>::max() (indeed defined in limits.h). But your solution also works! I have updated the code, also including some compatibility update with the development version of Bio++.

Cheers,

Julien.
